# Generated by Django 5.2.6 on 2025-10-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('fecha', models.DateField(verbose_name='')),
                ('disponible', models.CharField(max_length=5)),
            ],
        ),
    ]
